// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavanNah.DataAccess.Contexts;

#nullable disable

namespace SavanNah.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817190449_Add_Identity")]
    partial class Add_Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SavanNah.Models.Models.BrandModel.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "South Korean multinational electronics and tech corporation",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Description = "American technology company known for iPhone and Mac",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Japanese conglomerate specialising in electronics and entertainment",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Description = "American sportswear and athletic footwear brand",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 5,
                            Description = "German multinational sportswear and clothing brand",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Japanese multinational automotive manufacturer",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Leading international book publisher",
                            Name = "Penguin"
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.CategoryModel.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apparel and fashion items",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Automobiles and automotive accessories",
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Essential appliances for the modern home",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Consumer electronics and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books across all genres and disciplines",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.CategoryProductModel.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductsId = 10
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.ProductModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            Description = "Comfortable cotton T-shirt",
                            Discount = 0m,
                            Image = "",
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            Description = "Stylish denim jeans",
                            Discount = 0m,
                            Image = "",
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 6,
                            Description = "Fast and luxurious sports car",
                            Discount = 0m,
                            Image = "",
                            Name = "Sports Car",
                            Price = 75000.00m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 6,
                            Description = "Reliable family car",
                            Discount = 0m,
                            Image = "",
                            Name = "Family Sedan",
                            Price = 25000.00m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Description = "Large capacity refrigerator",
                            Discount = 0m,
                            Image = "",
                            Name = "Refrigerator",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Description = "Efficient washing machine",
                            Discount = 0m,
                            Image = "",
                            Name = "Washing Machine",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Description = "Latest model smartphone",
                            Discount = 0m,
                            Image = "",
                            Name = "Smartphone",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Description = "High performance laptop",
                            Discount = 0m,
                            Image = "",
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 7,
                            Description = "Bestselling novel",
                            Discount = 0m,
                            Image = "",
                            Name = "Fiction Book",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 7,
                            Description = "Educational science book",
                            Discount = 0m,
                            Image = "",
                            Name = "Science Book",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.RoleModel.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SavanNah.Models.Models.UserModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SavanNah.Models.Models.RoleModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SavanNah.Models.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SavanNah.Models.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SavanNah.Models.Models.RoleModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavanNah.Models.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SavanNah.Models.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavanNah.Models.Models.CategoryProductModel.CategoryProduct", b =>
                {
                    b.HasOne("SavanNah.Models.Models.CategoryModel.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavanNah.Models.Models.ProductModel.Product", "Products")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SavanNah.Models.Models.ProductModel.Product", b =>
                {
                    b.HasOne("SavanNah.Models.Models.BrandModel.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SavanNah.Models.Models.BrandModel.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SavanNah.Models.Models.CategoryModel.Category", b =>
                {
                    b.Navigation("CategoryProducts");
                });

            modelBuilder.Entity("SavanNah.Models.Models.ProductModel.Product", b =>
                {
                    b.Navigation("CategoryProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
