// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavanNah.DataAccess.Contexts;

#nullable disable

namespace SavanNah.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630230758_UpdateCategoriesTable")]
    partial class UpdateCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("SavanNah.Models.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "South Korean multinational electronics and tech corporation",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Description = "American technology company known for iPhone and Mac",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Japanese conglomerate specialising in electronics and entertainment",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Description = "American sportswear and athletic footwear brand",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 5,
                            Description = "German multinational sportswear and clothing brand",
                            Name = "Adidas"
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apparel and fashion items",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Automobiles and automotive accessories",
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Essential appliances for the modern home",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Consumer electronics and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books across all genres and disciplines",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("SavanNah.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Comfortable cotton T-shirt",
                            Discount = 0m,
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Stylish denim jeans",
                            Discount = 0m,
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Fast and luxurious sports car",
                            Discount = 0m,
                            Name = "Sports Car",
                            Price = 75000.00m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            CategoryId = 2,
                            Description = "Reliable family car",
                            Discount = 0m,
                            Name = "Family Sedan",
                            Price = 25000.00m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Large capacity refrigerator",
                            Discount = 0m,
                            Name = "Refrigerator",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Efficient washing machine",
                            Discount = 0m,
                            Name = "Washing Machine",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Latest model smartphone",
                            Discount = 0m,
                            Name = "Smartphone",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            CategoryId = 4,
                            Description = "High performance laptop",
                            Discount = 0m,
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 4,
                            CategoryId = 5,
                            Description = "Bestselling novel",
                            Discount = 0m,
                            Name = "Fiction Book",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            CategoryId = 5,
                            Description = "Educational science book",
                            Discount = 0m,
                            Name = "Science Book",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("SavanNah.Models.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavanNah.Models.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavanNah.Models.Models.Product", b =>
                {
                    b.HasOne("SavanNah.Models.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SavanNah.Models.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
